- name: variables form inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello i am learning {{ COURSE }},  Duration: {{ DURATION }}, and Traner: {{ TRAINER }}"