- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raju,Krish"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Ramesh')}}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        Name: ansible
        Duration: 10 hrs
        Trainer: Siva
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items }}"
  
  - name: convert list into map
    vars:
      course:
        - {'key': 'Name', 'value': 'ansible'}
        - {'key': 'Duration', 'value': '10 hrs'}
        - {'key': 'Trainer', 'value': 'Siva'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "need uppcase this one"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: ip address is valid or not
    vars:
      ip: "300.342.560.123"
    ansible.builtin.debug:
      msg: "Hello {{ ip | ansible.utils.ipaddr }}"