- name: shell vs command modules
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    #ansible.builtin.command: "ls -ltr > /tmp/output_1.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output_1.txt"